language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.7.0a3"
matrix:
  allow_failures:
    - python: 3.7.0a3
before_install:
  - pip install --upgrade setuptools
install:
  - pip install flake8 codecov
before_script:
  - flake8 .
script: python setup.py nosetests
after_success:
  - codecov
